"""create cortex.diary table

Revision ID: ea2a504655cd
Revises: ced79d1d76e3
Create Date: 2026-05-29 12:21:02.545050

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea2a504655cd"
down_revision: str | Sequence[str] | None = "ced79d1d76e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create cortex.diary — required by the diary tools and the start/finish skills.

    Shape matches what add_to_diary / read_from_diary query: an
    auto-incrementing id, non-empty content, and a created_at the tools both
    insert and order/filter by.
    """
    op.execute(
        "CREATE TABLE cortex.diary ("
        " id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
        " content text NOT NULL,"
        " created_at timestamptz NOT NULL DEFAULT now()"
        ")"
    )


def downgrade() -> None:
    """Drop cortex.diary."""
    op.execute("DROP TABLE cortex.diary")
