--
-- PostgreSQL database dump
--

\restrict KdvAn16CMiI6t0GH2KPkSrDFmj2Vf8rZ95vkYqnzc3hafpuXaXHMjTKxfXeapss

-- Dumped from database version 17.10 (Debian 17.10-1.pgdg12+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: cortex; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA cortex;


--
-- Name: sage; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA sage;


--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


--
-- Name: memories_tsv_trigger(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.memories_tsv_trigger() RETURNS trigger
    LANGUAGE plpgsql
    AS $$ BEGIN NEW.content_tsv := to_tsvector('english', NEW.content); RETURN NEW; END; $$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: diary; Type: TABLE; Schema: cortex; Owner: -
--

CREATE TABLE cortex.diary (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: diary_id_seq; Type: SEQUENCE; Schema: cortex; Owner: -
--

ALTER TABLE cortex.diary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cortex.diary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: memories; Type: TABLE; Schema: cortex; Owner: -
--

CREATE TABLE cortex.memories (
    id integer NOT NULL,
    content text NOT NULL,
    embedding public.vector(768),
    metadata jsonb DEFAULT '{}'::jsonb,
    forgotten boolean DEFAULT false,
    content_tsv tsvector,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: memories_id_seq; Type: SEQUENCE; Schema: cortex; Owner: -
--

CREATE SEQUENCE cortex.memories_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: memories_id_seq; Type: SEQUENCE OWNED BY; Schema: cortex; Owner: -
--

ALTER SEQUENCE cortex.memories_id_seq OWNED BY cortex.memories.id;


--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id integer NOT NULL,
    "timestamp" timestamp with time zone DEFAULT now(),
    role text NOT NULL,
    content text NOT NULL,
    session_id text,
    embedding public.vector(768)
);


--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.messages_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: messages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.messages_id_seq OWNED BY public.messages.id;


--
-- Name: rosemary_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rosemary_sessions (
    session_id text NOT NULL,
    title text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: summaries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.summaries (
    id integer NOT NULL,
    period_start timestamp with time zone NOT NULL,
    period_end timestamp with time zone NOT NULL,
    summary text NOT NULL,
    capsule_type text DEFAULT 'today_so_far'::text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: summaries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.summaries_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: summaries_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.summaries_id_seq OWNED BY public.summaries.id;


--
-- Name: conversations; Type: TABLE; Schema: sage; Owner: -
--

CREATE TABLE sage.conversations (
    id integer NOT NULL,
    openai_id text NOT NULL,
    title text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    model text,
    message_count integer DEFAULT 0
);


--
-- Name: messages; Type: TABLE; Schema: sage; Owner: -
--

CREATE TABLE sage.messages (
    id integer NOT NULL,
    conversation_id integer NOT NULL,
    speaker text NOT NULL,
    content text NOT NULL,
    content_type text DEFAULT 'text'::text NOT NULL,
    searchable boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone,
    sequence integer NOT NULL,
    embedding public.vector(768),
    content_tsv tsvector GENERATED ALWAYS AS (
CASE
    WHEN searchable THEN to_tsvector('english'::regconfig, content)
    ELSE NULL::tsvector
END) STORED,
    CONSTRAINT sage_messages_speaker_check CHECK ((speaker = ANY (ARRAY['kylee'::text, 'sage'::text, 'tool'::text])))
);


--
-- Name: sage_conversations_id_seq; Type: SEQUENCE; Schema: sage; Owner: -
--

CREATE SEQUENCE sage.sage_conversations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sage_conversations_id_seq; Type: SEQUENCE OWNED BY; Schema: sage; Owner: -
--

ALTER SEQUENCE sage.sage_conversations_id_seq OWNED BY sage.conversations.id;


--
-- Name: sage_messages_id_seq; Type: SEQUENCE; Schema: sage; Owner: -
--

CREATE SEQUENCE sage.sage_messages_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sage_messages_id_seq; Type: SEQUENCE OWNED BY; Schema: sage; Owner: -
--

ALTER SEQUENCE sage.sage_messages_id_seq OWNED BY sage.messages.id;


--
-- Name: memories id; Type: DEFAULT; Schema: cortex; Owner: -
--

ALTER TABLE ONLY cortex.memories ALTER COLUMN id SET DEFAULT nextval('cortex.memories_id_seq'::regclass);


--
-- Name: messages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages ALTER COLUMN id SET DEFAULT nextval('public.messages_id_seq'::regclass);


--
-- Name: summaries id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.summaries ALTER COLUMN id SET DEFAULT nextval('public.summaries_id_seq'::regclass);


--
-- Name: conversations id; Type: DEFAULT; Schema: sage; Owner: -
--

ALTER TABLE ONLY sage.conversations ALTER COLUMN id SET DEFAULT nextval('sage.sage_conversations_id_seq'::regclass);


--
-- Name: messages id; Type: DEFAULT; Schema: sage; Owner: -
--

ALTER TABLE ONLY sage.messages ALTER COLUMN id SET DEFAULT nextval('sage.sage_messages_id_seq'::regclass);


--
-- Name: diary diary_pkey; Type: CONSTRAINT; Schema: cortex; Owner: -
--

ALTER TABLE ONLY cortex.diary
    ADD CONSTRAINT diary_pkey PRIMARY KEY (id);


--
-- Name: memories memories_pkey; Type: CONSTRAINT; Schema: cortex; Owner: -
--

ALTER TABLE ONLY cortex.memories
    ADD CONSTRAINT memories_pkey PRIMARY KEY (id);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: rosemary_sessions rosemary_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rosemary_sessions
    ADD CONSTRAINT rosemary_sessions_pkey PRIMARY KEY (session_id);


--
-- Name: summaries summaries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.summaries
    ADD CONSTRAINT summaries_pkey PRIMARY KEY (id);


--
-- Name: conversations sage_conversations_openai_id_key; Type: CONSTRAINT; Schema: sage; Owner: -
--

ALTER TABLE ONLY sage.conversations
    ADD CONSTRAINT sage_conversations_openai_id_key UNIQUE (openai_id);


--
-- Name: conversations sage_conversations_pkey; Type: CONSTRAINT; Schema: sage; Owner: -
--

ALTER TABLE ONLY sage.conversations
    ADD CONSTRAINT sage_conversations_pkey PRIMARY KEY (id);


--
-- Name: messages sage_messages_conversation_id_sequence_key; Type: CONSTRAINT; Schema: sage; Owner: -
--

ALTER TABLE ONLY sage.messages
    ADD CONSTRAINT sage_messages_conversation_id_sequence_key UNIQUE (conversation_id, sequence);


--
-- Name: messages sage_messages_pkey; Type: CONSTRAINT; Schema: sage; Owner: -
--

ALTER TABLE ONLY sage.messages
    ADD CONSTRAINT sage_messages_pkey PRIMARY KEY (id);


--
-- Name: memories_content_tsv_idx; Type: INDEX; Schema: cortex; Owner: -
--

CREATE INDEX memories_content_tsv_idx ON cortex.memories USING gin (content_tsv);


--
-- Name: memories_created_at_idx; Type: INDEX; Schema: cortex; Owner: -
--

CREATE INDEX memories_created_at_idx ON cortex.memories USING btree (created_at);


--
-- Name: memories_embedding_idx; Type: INDEX; Schema: cortex; Owner: -
--

CREATE INDEX memories_embedding_idx ON cortex.memories USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: memories_forgotten_idx; Type: INDEX; Schema: cortex; Owner: -
--

CREATE INDEX memories_forgotten_idx ON cortex.memories USING btree (forgotten);


--
-- Name: idx_summaries_period_start; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_summaries_period_start ON public.summaries USING btree (period_start DESC);


--
-- Name: messages_unique_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX messages_unique_idx ON public.messages USING btree ("timestamp", role, md5(content));


--
-- Name: sage_conversations_created_idx; Type: INDEX; Schema: sage; Owner: -
--

CREATE INDEX sage_conversations_created_idx ON sage.conversations USING btree (created_at);


--
-- Name: sage_messages_conversation_idx; Type: INDEX; Schema: sage; Owner: -
--

CREATE INDEX sage_messages_conversation_idx ON sage.messages USING btree (conversation_id);


--
-- Name: sage_messages_embedding_idx; Type: INDEX; Schema: sage; Owner: -
--

CREATE INDEX sage_messages_embedding_idx ON sage.messages USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: sage_messages_searchable_idx; Type: INDEX; Schema: sage; Owner: -
--

CREATE INDEX sage_messages_searchable_idx ON sage.messages USING btree (searchable) WHERE (searchable = true);


--
-- Name: sage_messages_speaker_idx; Type: INDEX; Schema: sage; Owner: -
--

CREATE INDEX sage_messages_speaker_idx ON sage.messages USING btree (speaker);


--
-- Name: sage_messages_tsv_idx; Type: INDEX; Schema: sage; Owner: -
--

CREATE INDEX sage_messages_tsv_idx ON sage.messages USING gin (content_tsv);


--
-- Name: memories memories_tsv_update; Type: TRIGGER; Schema: cortex; Owner: -
--

CREATE TRIGGER memories_tsv_update BEFORE INSERT OR UPDATE ON cortex.memories FOR EACH ROW EXECUTE FUNCTION public.memories_tsv_trigger();


--
-- Name: messages sage_messages_conversation_id_fkey; Type: FK CONSTRAINT; Schema: sage; Owner: -
--

ALTER TABLE ONLY sage.messages
    ADD CONSTRAINT sage_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES sage.conversations(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict KdvAn16CMiI6t0GH2KPkSrDFmj2Vf8rZ95vkYqnzc3hafpuXaXHMjTKxfXeapss

